apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kargo
  version: 1.2.0
  repo: oci://ghcr.io/akuity/kargo-charts
  releaseName: kargo
  valuesFile: values.yaml
  ## IF needed
  #includeCRDs: true

