apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: ConfigMap
    name: kargo-controller
    version: v1
  patch: |
    - op: replace
      path: /data/LOG_LEVEL
      value: "DEBUG"
